name: Daily build

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      # Build Ballerina Project
      - name: Ballerina Build
        run: bal pack ./ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        working-directory: ./ballerina
        run: bal test --test-report --code-coverage --coverage-format=xml
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
          ACCESS_KEY_OR_SAS: ${{ secrets.ACCESS_KEY_OR_SAS }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
